main:
  - name: Bio
    url: "#bio"
    weight: 10

  - name: Publications
    url: "#publications"
    weight: 20

  - name: Teaching & Mentoring
    url: "#teaching"
    weight: 30

  - name: Public Engagement
    url: "#engagement"
    weight: 40

  - name: Skills & Methods
    url: "#skills"
    weight: 50

  - name: Additional Training
    url: "#training"
    weight: 60

  - name: Contact
    url: "#contact"
    weight: 70
