main:
  - name: Additional Training
    url: "#training"
    weight: 10

  - name: Teaching & Mentoring
    url: "#teaching"
    weight: 20

  - name: Scientific Engagement
    url: "#engagement"
    weight: 30

  - name: Skills & Methods
    url: "#skills"
    weight: 40

  - name: Awards
    url: "#awards"
    weight: 50
    
  - name: Presentations
    url: "#presentations"
    weight: 60

  - name: Publications
    url: "#publications"
    weight: 70
